apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::972913963856:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1BFU727ZWRGDQ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::972913963856:role/UdacityFlaskDeployCBKubectlRole
      username: build   
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-08T18:29:15Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1589"
  uid: 0a7a4307-9803-487f-bbb1-69f221305a0e
